version: '3.8'

services:
  nats:
    image: nats:2.11
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -m 8222
    restart: always

  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=7fb3232841bd35feb7a5
      - DOCKER_INFLUXDB_INIT_ORG=acme_corp
      - DOCKER_INFLUXDB_INIT_BUCKET=the_bucket
    restart: always

  data_ingestion:
    build:
      context: ./data_ingestion
    depends_on:
      - nats

  processing:
    build:
      context: ./processing
    depends_on:
      - nats
      - influxdb

  historian:
    build:
      context: ./historian
    depends_on:
      - influxdb

  alerting:
    build:
      context: ./alerting
    depends_on:
      - nats

volumes:
  influxdb2-data:
  influxdb2-config:
