version: "3.9"
services:
  nats:
    image: nats:2.11
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -m 8222
    restart: always

  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
    restart: always
  
  data_ingestion:
    build:
      context: ./data_ingestion
    depends_on:
      - nats
    restart: on-failure
  
  processing:
    build:
      context: ./processing
    depends_on:
      - nats
      - influxdb
    environment:
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - ORG=${ORG}
      - BUCKET=${BUCKET}

  alerting:
    build: ./alerting
    depends_on:
      - nats
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
    environment:
      - ALERT_THRESHOLD_TEMP=${ALERT_THRESHOLD_TEMP}
      - EMAIL_USER=${EMAIL_USER}
      - ALERT_RECIPIENT=${ALERT_RECIPIENT}
      - EMAIL_PASS=${EMAIL_PASS}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222"]
      interval: 30s
      timeout: 5s
      retries: 3

  historian:
    build:
      context: ./historian
    ports:
      - "8088:8088"
    environment:
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - ORG=${ORG}
      - BUCKET=${BUCKET}
    depends_on:
      - influxdb

volumes:
  influxdb2-data:
  influxdb2-config:
